from datetime import datetime, time
from utils.market_manager import GLOBAL_MARKET_MANAGER

def get_current_datetime(trigger_time: str) -> str:
    """Get current time"""
    if trigger_time:
        return trigger_time
    else:
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def normalize_trade_date_compact(trade_date: str) -> str:
    """Normalize trade date to akshare-compatible YYYYMMDD."""
    normalized = str(trade_date).strip().replace("-", "").replace("/", "")
    if len(normalized) != 8 or not normalized.isdigit():
        raise ValueError(f"Invalid trade date: {trade_date}")
    return normalized


def get_previous_trading_date(trigger_time: str, output_format: str = "%Y%m%d") -> str:
    """获取trigger_time的上一个交易日
    
    Args:
        trigger_time (str): 触发时间，格式：YYYY-MM-DD HH:MM:SS
    
    Returns:
        str: 上一个交易日，格式：YYYYMMDD
    """
    # 解析trigger_time
    trigger_datetime = datetime.strptime(trigger_time, '%Y-%m-%d %H:%M:%S')
    trigger_date = trigger_datetime.strftime('%Y%m%d')
    
    # 获取交易日列表
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name="CN-Stock")
    
    # 找到上一个交易日
    previous_dates = [dt for dt in trade_dates if dt < trigger_date]
    previous_trading_date = previous_dates[-1]
    previous_trading_datetime = previous_trading_date[:4] + "-" + previous_trading_date[4:6] + "-" + previous_trading_date[6:] + " " + trigger_time.split(" ")[1]
    previous_trading_date_formatted = datetime.strptime(previous_trading_datetime, "%Y-%m-%d %H:%M:%S").strftime(output_format)
    return previous_trading_date_formatted


def is_trading_day(date: str, market_name: str = "CN-Stock") -> bool:
    """判断日期是否为交易日，date 支持 YYYYMMDD 或 YYYY-MM-DD。"""
    normalized_date = date.replace("-", "")
    return normalized_date in GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)


def get_latest_completed_trading_date(
    trigger_time: str,
    output_format: str = "%Y%m%d",
    market_name: str = "CN-Stock",
    market_close_time: str = "15:00:00",
) -> str:
    """获取触发时刻之前最近一个已经收盘的交易日。

    盘后运行应使用当天交易数据；盘中或非交易日运行则回退到最近已完成交易日。
    """
    trigger_datetime = datetime.strptime(trigger_time, "%Y-%m-%d %H:%M:%S")
    trigger_date = trigger_datetime.strftime("%Y%m%d")
    close_time = time.fromisoformat(market_close_time)

    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)
    if trigger_date in trade_dates and trigger_datetime.time() >= close_time:
        target_trade_date = trigger_date
    else:
        completed_dates = [dt for dt in trade_dates if dt < trigger_date]
        if not completed_dates:
            raise ValueError(f"No completed trading dates found before {trigger_date}")
        target_trade_date = completed_dates[-1]

    target_datetime = (
        target_trade_date[:4]
        + "-"
        + target_trade_date[4:6]
        + "-"
        + target_trade_date[6:]
        + " "
        + trigger_time.split(" ")[1]
    )
    return datetime.strptime(target_datetime, "%Y-%m-%d %H:%M:%S").strftime(output_format)


def get_trading_date_range(
    end_date: str,
    count: int,
    market_name: str = "CN-Stock",
    output_format: str = "%Y%m%d",
    include_end: bool = False,
) -> tuple[str, str]:
    """获取交易日区间。

    Args:
        end_date: 锚定交易日，格式 YYYYMMDD
        count: 交易日数量
        market_name: 市场名称
        output_format: 返回日期格式
        include_end: True 表示区间含 end_date；False 表示前 count 个交易日（不含 end_date）

    Returns:
        (start_date, range_end_date) 格式化后的起止交易日

    Generated by AI Assistant - 2026-08-05 17:45:00
    """
    normalized_end = end_date.replace("-", "")
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)
    if include_end:
        eligible = [dt for dt in trade_dates if dt <= normalized_end]
    else:
        eligible = [dt for dt in trade_dates if dt < normalized_end]
    if not eligible:
        raise ValueError(f"No trading dates found before/on {normalized_end}")

    window = eligible[-count:] if len(eligible) >= count else eligible
    start_date = window[0]
    range_end_date = window[-1]
    start_dt = datetime.strptime(start_date, "%Y%m%d")
    end_dt = datetime.strptime(range_end_date, "%Y%m%d")
    return start_dt.strftime(output_format), end_dt.strftime(output_format)


def get_previous_trading_dates(
    end_date: str,
    count: int,
    market_name: str = "CN-Stock",
) -> list[str]:
    """获取 end_date 之前的 count 个交易日（不含 end_date）。

    Generated by AI Assistant - 2026-08-05 17:50:00
    """
    normalized_end = end_date.replace("-", "")
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)
    previous = [dt for dt in trade_dates if dt < normalized_end]
    return previous[-count:] if len(previous) >= count else previous


if __name__ == "__main__":
    print(get_current_datetime("2025-01-01 10:00:00"))
    print(get_previous_trading_date("2025-01-01 10:00:00"))
