from datetime import datetime
from utils.market_manager import GLOBAL_MARKET_MANAGER

def get_current_datetime(trigger_time: str) -> str:
    """Get current time"""
    if trigger_time:
        return trigger_time
    else:
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def get_previous_trading_date(trigger_time: str, output_format: str = "%Y%m%d") -> str:
    """获取trigger_time的上一个交易日
    
    Args:
        trigger_time (str): 触发时间，格式：YYYY-MM-DD HH:MM:SS
    
    Returns:
        str: 上一个交易日，格式：YYYYMMDD
    """
    # 解析trigger_time
    trigger_datetime = datetime.strptime(trigger_time, '%Y-%m-%d %H:%M:%S')
    trigger_date = trigger_datetime.strftime('%Y%m%d')
    
    # 获取交易日列表
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name="CN-Stock")
    
    # 找到上一个交易日
    previous_dates = [dt for dt in trade_dates if dt < trigger_date]
    previous_trading_date = previous_dates[-1]
    previous_trading_datetime = previous_trading_date[:4] + "-" + previous_trading_date[4:6] + "-" + previous_trading_date[6:] + " " + trigger_time.split(" ")[1]
    previous_trading_date_formatted = datetime.strptime(previous_trading_datetime, "%Y-%m-%d %H:%M:%S").strftime(output_format)
    return previous_trading_date_formatted


def get_trading_date_range(
    end_date: str,
    count: int,
    market_name: str = "CN-Stock",
    output_format: str = "%Y%m%d",
    include_end: bool = False,
) -> tuple[str, str]:
    """获取交易日区间。

    Args:
        end_date: 锚定交易日，格式 YYYYMMDD
        count: 交易日数量
        market_name: 市场名称
        output_format: 返回日期格式
        include_end: True 表示区间含 end_date；False 表示前 count 个交易日（不含 end_date）

    Returns:
        (start_date, range_end_date) 格式化后的起止交易日

    Generated by AI Assistant - 2026-08-05 17:45:00
    """
    normalized_end = end_date.replace("-", "")
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)
    if include_end:
        eligible = [dt for dt in trade_dates if dt <= normalized_end]
    else:
        eligible = [dt for dt in trade_dates if dt < normalized_end]
    if not eligible:
        raise ValueError(f"No trading dates found before/on {normalized_end}")

    window = eligible[-count:] if len(eligible) >= count else eligible
    start_date = window[0]
    range_end_date = window[-1]
    start_dt = datetime.strptime(start_date, "%Y%m%d")
    end_dt = datetime.strptime(range_end_date, "%Y%m%d")
    return start_dt.strftime(output_format), end_dt.strftime(output_format)


def get_previous_trading_dates(
    end_date: str,
    count: int,
    market_name: str = "CN-Stock",
) -> list[str]:
    """获取 end_date 之前的 count 个交易日（不含 end_date）。

    Generated by AI Assistant - 2026-08-05 17:50:00
    """
    normalized_end = end_date.replace("-", "")
    trade_dates = GLOBAL_MARKET_MANAGER.get_trade_date(market_name=market_name)
    previous = [dt for dt in trade_dates if dt < normalized_end]
    return previous[-count:] if len(previous) >= count else previous


if __name__ == "__main__":
    print(get_current_datetime("2025-01-01 10:00:00"))
    print(get_previous_trading_date("2025-01-01 10:00:00"))