"""
Agent 级别报告生成与汇总刷新。
"""
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from config.config import PROJECT_ROOT


def _safe_trigger_time(trigger_time: str) -> str:
    return trigger_time.replace(" ", "_").replace(":", "-")


def _results_dir() -> Path:
    return PROJECT_ROOT / "agents_workspace" / "results"


def _get_text(cn_text: str, en_text: str) -> str:
    market_type = os.environ.get("CONTEST_TRADE_MARKET", "CN-Stock")
    return en_text if market_type == "US-Stock" else cn_text


def _clean_context(context_string: str) -> str:
    return re.sub(r"\[Batch \d+\]", "", context_string or "").strip()


def generate_data_agent_report(factor: Dict) -> Optional[Path]:
    """
    为单个 Data Agent 生成 Markdown 报告。
    @generated AI Assistant - 2026-08-05 19:32:00
    """
    agent_name = factor.get("agent_name")
    trigger_time = factor.get("trigger_time")
    if not agent_name or not trigger_time:
        return None

    safe_time = _safe_trigger_time(trigger_time)
    report_dir = _results_dir() / "data_reports" / agent_name
    report_dir.mkdir(parents=True, exist_ok=True)
    save_path = report_dir / f"{safe_time}.md"

    context_string = _clean_context(factor.get("context_string", ""))
    content = f"""# {_get_text('数据分析报告', 'Data Analysis Report')} — {agent_name}

**{_get_text('分析时间', 'Analysis Time')}**: {trigger_time}  
**{_get_text('数据代理', 'Data Agent')}**: {agent_name}  
**{_get_text('报告生成时间', 'Report Generation Time')}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## {_get_text('分析内容', 'Analysis Content')}

{context_string if context_string else _get_text('暂无分析内容', 'No analysis content available')}

---

## {_get_text('免责声明', 'Disclaimer')}

{_get_text('本报告由 ContestTrade 自动生成，仅供参考，不构成投资建议。', 'This report is auto-generated by ContestTrade for reference only.')}
"""
    save_path.write_text(content, encoding="utf-8")
    return save_path


def generate_research_agent_report(result: Dict, agent_name: str) -> Optional[Path]:
    """
    为单个 Research Agent 生成 Markdown 报告。
    @generated AI Assistant - 2026-08-05 19:32:00
    """
    trigger_time = result.get("trigger_time")
    if not trigger_time:
        return None

    safe_time = _safe_trigger_time(trigger_time)
    report_dir = _results_dir() / "research_reports" / agent_name
    report_dir.mkdir(parents=True, exist_ok=True)
    save_path = report_dir / f"{safe_time}.md"

    final_result = (result.get("final_result") or "").strip()
    belief = result.get("belief") or ""
    task = result.get("task") or ""

    content = f"""# {_get_text('研究报告', 'Research Report')} — {agent_name}

**{_get_text('分析时间', 'Analysis Time')}**: {trigger_time}  
**{_get_text('研究代理', 'Research Agent')}**: {agent_name}  
**{_get_text('交易信念', 'Trading Belief')}**: {belief}  
**{_get_text('报告生成时间', 'Report Generation Time')}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## {_get_text('研究任务', 'Research Task')}

{task if task else "—"}

---

## {_get_text('研究结论', 'Research Conclusion')}

{final_result if final_result else _get_text('暂无研究结论', 'No research conclusion available')}

---

## {_get_text('免责声明', 'Disclaimer')}

{_get_text('本报告由 ContestTrade 自动生成，仅供参考，不构成投资建议。', 'This report is auto-generated by ContestTrade for reference only.')}
"""
    save_path.write_text(content, encoding="utf-8")
    return save_path


def load_factors_for_trigger(trigger_time: str) -> Dict:
    """
    加载指定 trigger_time 下所有已完成的 Data Agent 因子。
    @generated AI Assistant - 2026-08-05 19:32:00
    """
    factors_data = {"trigger_time": trigger_time, "agents": {}}
    timestamp_str = _safe_trigger_time(trigger_time)
    factors_dir = PROJECT_ROOT / "agents_workspace" / "factors"
    if not factors_dir.exists():
        return factors_data

    for agent_dir in factors_dir.iterdir():
        if not agent_dir.is_dir():
            continue
        files = list(agent_dir.glob(f"{timestamp_str}*.json"))
        if not files:
            continue
        with open(files[0], "r", encoding="utf-8") as f:
            factors_data["agents"][agent_dir.name] = json.load(f)
    return factors_data


def refresh_combined_data_report(trigger_time: str) -> Optional[Path]:
    """
    根据当前已完成的 Data Agent 因子，刷新汇总数据报告。
    @generated AI Assistant - 2026-08-05 19:32:00
    """
    factors_data = load_factors_for_trigger(trigger_time)
    agents = factors_data.get("agents") or {}
    if not agents:
        return None

    safe_time = _safe_trigger_time(trigger_time)
    report_dir = _results_dir() / "data_reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    save_path = report_dir / f"data_report_{safe_time}.md"

    lines = [
        f"# ContestTrade {_get_text('数据分析汇总报告', 'Data Analysis Summary Report')}",
        "",
        f"**{_get_text('分析时间', 'Analysis Time')}**: {trigger_time}  ",
        f"**{_get_text('已完成代理', 'Completed Agents')}**: {len(agents)}  ",
        f"**{_get_text('报告生成时间', 'Report Generation Time')}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "---",
        "",
    ]
    for agent_name, agent_data in agents.items():
        lines.append(f"## {agent_name}")
        lines.append("")
        context = _clean_context(agent_data.get("context_string", ""))
        lines.append(context if context else _get_text("暂无分析内容", "No analysis content available"))
        lines.append("")
        lines.append("---")
        lines.append("")

    save_path.write_text("\n".join(lines), encoding="utf-8")
    return save_path
